// Testcases voor de post-processing benchmark.
//
// Twee soorten:
// - DEEP_CASES: strikte controles per prompt-regel, vooral en/nl plus
//   de/fr/es/it/pt. Elke check telt mee voor de score.
// - SMOKE_RAW: een korte ruwe transcriptie per Handy-taal. Daarop gelden
//   automatische controles (geen filler, geen code fences, niet leeg).
//   Smoke-tests bewijzen dat een model de taal aankan zonder te crashen,
//   te weigeren of naar het Engels te vluchten. De volledige output staat
//   in results.json voor handmatige controle.
//
// Check-velden per testcase:
//   contain: substrings die in de output moeten staan
//   notContain: substrings die er niet in mogen staan
//   match: regex-strings (zonder vlaggen, case-sensitive tenzij (?i) prefix)
//   notMatch: regex-strings die niet mogen matchen
//   exact: output moet na trimmen exact hieraan gelijk zijn

export const DEEP_CASES = [
  {
    id: "en-filler", lang: "en", cat: "filler",
    raw: "um hello uh how are you today",
    contain: ["Hello", "how are you"],
    notContain: ["um", "uh"],
    match: ["[.?]$"],
  },
  {
    id: "en-question", lang: "en", cat: "spelling",
    raw: "Hey uhh what is the um time",
    contain: ["What is the time"],
    notContain: ["uhh", "um"],
    match: ["\\?$"],
  },
  {
    id: "en-numbers", lang: "en", cat: "numbers",
    raw: "i bought twenty-five apples with ten percent discount",
    contain: ["25", "10%"],
    notContain: ["twenty-five", "ten percent"],
  },
  {
    id: "en-money", lang: "en", cat: "numbers",
    raw: "that costs five dollars please",
    contain: ["$5"],
    notContain: ["five dollars"],
  },
  {
    id: "en-punct", lang: "en", cat: "punctuation",
    raw: "hello comma how are you question mark",
    contain: ["Hello,", "?"],
    notContain: ["comma", "question mark"],
  },
  {
    id: "en-math", lang: "en", cat: "math",
    raw: "add three plus four together",
    contain: [],
    notContain: ["plus"],
    match: ["3\\s*\\+\\s*4|\\b7\\b"],
  },
  {
    id: "en-list", lang: "en", cat: "list",
    raw: "my shopping list apples bananas and milk",
    contain: ["apples", "bananas", "milk"],
    notContain: ["```"],
    match: ["(?m)^\\s*[\\*\\-]\\s+\\S"],
  },
  {
    id: "en-email", lang: "en", cat: "email",
    raw: "hi john comma thanks for your email period best regards mike",
    contain: ["Hi John", "Best regards", "Mike"],
    notContain: ["comma", "period", "```"],
  },
  {
    id: "en-emoji", lang: "en", cat: "emoji",
    raw: "that party was fire emoji",
    contain: ["\u{1F525}"],
    notContain: ["fire emoji"],
  },
  {
    id: "en-newline", lang: "en", cat: "layout",
    raw: "first line new line second line",
    contain: ["first line", "second line"],
    notContain: ["new line"],
    match: ["first line\\nsecond line"],
  },
  {
    id: "en-no-fences", lang: "en", cat: "format",
    raw: "hello how are you today",
    contain: ["Hello"],
    notContain: ["```", "Here is", "cleaned text"],
  },
  {
    id: "en-helium", lang: "en", cat: "helium",
    raw: "hello world this should be blocked",
    activeWindow: "Helium - voice notes",
    exact: "NULL",
  },
  {
    id: "nl-filler", lang: "nl", cat: "filler",
    raw: "ehm hallo zeg maar hoe gaat het met jou",
    contain: ["Hallo", "hoe gaat het"],
    notContain: ["ehm", "zeg maar"],
  },
  {
    id: "nl-numbers", lang: "nl", cat: "numbers",
    raw: "dat kost vijf euro met tien procent korting",
    contain: ["€5", "10%"],
    notContain: ["vijf euro", "tien procent"],
  },
  {
    id: "nl-math", lang: "nl", cat: "math",
    raw: "reken uit drie keer vier",
    contain: [],
    notContain: ["keer"],
    match: ["3\\s*\\*\\s*4|\\b12\\b"],
  },
  {
    id: "nl-email", lang: "nl", cat: "email",
    raw: "beste jan komma hoe gaat het met je vraagteken vriendelijke groet piet",
    contain: ["Beste Jan", "Vriendelijke groet", "Piet"],
    notContain: ["komma", "vraagteken", "```"],
  },
  {
    id: "nl-punct", lang: "nl", cat: "punctuation",
    raw: "hallo punt hoe gaat het vraagteken",
    contain: ["Hallo.", "?"],
    notContain: ["vraagteken"],
  },
  {
    id: "nl-list", lang: "nl", cat: "list",
    raw: "boodschappenlijst appels bananen en melk",
    contain: ["appels", "bananen", "melk"],
    notContain: ["```"],
    match: ["(?m)^\\s*[\\*\\-]\\s+\\S"],
  },
  {
    id: "nl-alinea", lang: "nl", cat: "layout",
    raw: "eerste alinea nieuwe alinea tweede alinea",
    contain: ["eerste alinea", "tweede alinea"],
    notContain: ["nieuwe alinea"],
    match: ["\\n\\n"],
  },
  {
    id: "nl-email-addr", lang: "nl", cat: "email",
    raw: "mail me op jan at voorbeeld dot nl",
    contain: ["jan@voorbeeld.nl"],
    notContain: [" at ", " dot "],
  },
  {
    id: "de-basic", lang: "de", cat: "filler",
    raw: "äh hallo wie geht es dir heute",
    contain: ["Hallo", "Wie geht es dir"],
    notContain: ["äh"],
  },
  {
    id: "de-numbers", lang: "de", cat: "numbers",
    raw: "das kostet fünf Euro mit zehn Prozent Rabatt",
    contain: ["5", "10"],
    notContain: ["fünf Euro", "zehn Prozent", "```"],
  },
  {
    id: "fr-basic", lang: "fr", cat: "filler",
    raw: "euh bonjour comment ça va aujourd'hui",
    contain: ["Bonjour"],
    notContain: ["euh", "```"],
  },
  {
    id: "es-basic", lang: "es", cat: "filler",
    raw: "um hola cómo estás hoy",
    contain: ["Hola"],
    notContain: ["um", "```"],
  },
  {
    id: "it-basic", lang: "it", cat: "filler",
    raw: "um ciao come stai oggi",
    contain: ["Ciao"],
    notContain: ["um", "```"],
  },
  {
    id: "pt-basic", lang: "pt", cat: "filler",
    raw: "um olá como estás hoje",
    contain: ["Olá"],
    notContain: ["um", "```"],
  },
];

// Korte ruwe transcriptie per Handy-taal voor de smoke-test.
// Bewust overal met um/uh als filler, zodat dezelfde automatische
// controles voor elke taal gelden: filler weg, geen code fences, niet leeg.
export const SMOKE_RAW = {
  "en": "um hello how are you today uh thanks",
  "zh": "um 你好今天怎么样 uh 谢谢",
  "zh-Hans": "um 你好今天怎么样 uh 谢谢",
  "zh-Hant": "um 你好今日點樣 uh 多謝",
  "yue": "um 你好今日點呀 uh 唔該",
  "de": "äh hallo um wie geht es dir heute",
  "es": "um hola cómo estás hoy uh gracias",
  "ru": "um привет как дела сегодня uh спасибо",
  "ko": "um 안녕하세요 오늘 어때요 uh 감사합니다",
  "fr": "euh bonjour um comment ça va aujourd'hui",
  "ja": "um こんにちは今日はどうですか uh ありがとう",
  "pt": "um olá como estás hoje uh obrigado",
  "tr": "um merhaba bugün nasılsın uh teşekkürler",
  "pl": "um cześć jak się dziś masz uh dzięki",
  "ca": "um hola com estàs avui uh gràcies",
  "nl": "um hallo hoe gaat het vandaag uh bedankt",
  "ar": "um مرحبا كيف حالك اليوم uh شكرا",
  "sv": "um hej hur mår du idag uh tack",
  "it": "um ciao come stai oggi uh grazie",
  "id": "um halo apa kabar hari ini uh terima kasih",
  "hi": "um नमस्ते आज कैसे हो uh धन्यवाद",
  "fi": "um hei miten voit tänään uh kiitos",
  "vi": "um xin chào hôm nay bạn thế nào uh cảm ơn",
  "he": "um שלום מה שלומך היום uh תודה",
  "uk": "um привіт як справи сьогодні uh дякую",
  "el": "um γεια σου τι κάνεις σήμερα uh ευχαριστώ",
  "ms": "um hello apa khabar hari ini uh terima kasih",
  "cs": "um ahoj jak se dnes máš uh díky",
  "ro": "um bună cum ești astăzi uh mulțumesc",
  "da": "um hej hvordan har du det i dag uh tak",
  "hu": "um szia hogy vagy ma uh köszönöm",
  "ta": "um வணக்கம் இன்று எப்படி uh நன்றி",
  "no": "um hei hvordan har du det i dag uh takk",
  "th": "um สวัสดีวันนี้เป็นอย่างไร uh ขอบคุณ",
  "ur": "um السلام علیکم آج کیا حال ہے uh شکریہ",
  "hr": "um bok kako si danas uh hvala",
  "bg": "um здравей как си днес uh благодаря",
  "lt": "um labas kaip sekasi šiandien uh ačiū",
  "la": "um salve quomodo te hodie habes uh gratias",
  "mi": "um kia ora kei te pēhea koe uh ngā mihi",
  "ml": "um ഹലോ ഇന്ന് സുഖമാണോ uh നന്ദി",
  "cy": "um helo sut wyt ti heddiw uh diolch",
  "sk": "um ahoj ako sa dnes máš uh ďakujem",
  "te": "um హలో ఈరోజు ఎలా ఉన్నారు uh ధన్యవాదాలు",
  "fa": "um سلام امروز چطوری uh ممنون",
  "lv": "um sveiki kā tev šodien klājas uh paldies",
  "bn": "um হ্যালো আজ কেমন আছো uh ধন্যবাদ",
  "sr": "um здраво како си данас uh хвала",
  "az": "um salam bu gün necəsən uh sağ ol",
  "sl": "um živjo kako si danes uh hvala",
  "kn": "um ಹಲೋ ಇಂದು ಹೇಗಿದ್ದೀರಿ uh ಧನ್ಯವಾದ",
  "et": "um tere kuidas sul täna läheb uh aitäh",
  "mk": "um здраво како си денес uh благодарам",
  "br": "um demat penaos emaout hiziv uh trugarez",
  "eu": "um kaixo nola zaude gaur uh eskerrik asko",
  "is": "um hæ hvernig hefurðu það í dag uh takk",
  "hy": "um բարեւ ինչպես ես այսօր uh շնորհակալություն",
  "ne": "um नमस्ते आज कस्तो हुनुहुन्छ uh धन्यवाद",
  "mn": "um сайн уу өнөөдөр сайн уу uh баярлалаа",
  "bs": "um zdravo kako si danas uh hvala",
  "kk": "um сәлем бүгін қалайсың uh рахмет",
  "sq": "um përshëndetje si je sot uh faleminderit",
  "sw": "um habari unaendeleaje leo uh asante",
  "gl": "um ola como estás hoxe uh grazas",
  "mr": "um नमस्कार आज कसे आहात uh धन्यवाद",
  "pa": "um ਸਤ ਸ੍ਰੀ ਅਕਾਲ ਅੱਜ ਕੀ ਹਾਲ uh ਧੰਨਵਾਦ",
  "si": "um ආයුබෝවන් අද කොහොමද uh ස්තූතියි",
  "km": "um សួស្តីថ្ងៃនេះយ៉ាងម៉េច uh អរគុណ",
  "sn": "um mhoro wakadii nhasi uh ndatenda",
  "yo": "um bawo ni loni uh ese",
  "so": "um iska warran sidee tahay maanta uh mahadsanid",
  "af": "um hallo hoe gaan dit vandag uh dankie",
  "oc": "um bonjorn coma vas uèi uh mercé",
  "ka": "um გამარჯობა როგორ ხარ დღეს uh გმადლობ",
  "be": "um прывітанне як справы сёння uh дзякуй",
  "tg": "um салом имрӯз чӣ хел uh рахмат",
  "sd": "um السلام عليڪم اڄ ڪيئن آهين uh مهرباني",
  "gu": "um નમસ્તે આજે કેમ છો uh આભાર",
  "am": "um ሰላም ዛሬ እንዴት ነህ uh አመሰግናለሁ",
  "yi": "um שלום וויפל גייט עס היינט uh א דאנק",
  "lo": "um ສະບາຍດີມື້ນີ້ເປັນແນວໃດ uh ຂອບໃຈ",
  "uz": "um salom bugun yaxshimisiz uh rahmat",
  "fo": "um hey hvussu hevur tú tað í dag uh takk",
  "ht": "um bonjou kouman ou ye jodi a uh mèsi",
  "ps": "um سلام نن څنګه یې uh مننه",
  "tk": "um salam bu gün nähili uh sag bol",
  "nn": "um hei korleis har du det i dag uh takk",
  "mt": "um bonġu kif int illum uh grazzi",
  "sa": "um नमस्ते अद्य कथम् uh धन्यवादः",
  "lb": "um moien wéi geet et dir haut uh merci",
  "my": "um မင်္ဂလာပါနေ့သည်နေကောင်းလား uh ကျေးဇူးပါ",
  "bo": "um བཀྲ་ཤིས་བདེ་ལེགས་དེ་རིང་ག་འདྲ uh ཐུགས་རྗེ",
  "tl": "um kamusta kumusta ka ngayon uh salamat",
  "mg": "um salama manaoana androany uh misaotra",
  "as": "um নমস্কাৰ আজি কেনে uh ধন্যবাদ",
  "tt": "um сәлам бүген хәлләр ничек uh рәхмәт",
  "haw": "um aloha pehea ʻoe i kēia lā uh mahalo",
  "ln": "um mbote ndenge nini lelo uh mersi",
  "ha": "um sannu ya kake a yau uh na gode",
  "ba": "um сәләм бөгөн хәлдәр нисек uh рәхмәт",
  "jw": "um halo piye kabare dina iki uh matur nuwun",
  "su": "um halo kumaha damang dinten ieu uh hatur nuhun",
};
